spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

---
spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=TRUE;create=true

---

#spring:
#  profiles: dev
#  datasource:
#    url:
#    username:
#    password:
